---
# configure the cnode hosts 
- hosts: cnodes
  vars:
   var_remote_user: centos
   var_sudo: yes
   var_java_ver: 7u45
   var_java_build: b18
   var_ambari_server: "{{ lookup('file', '/home/centos/ambariserver.txt') }}"
  remote_user: "{{ var_remote_user }}"
  sudo: "{{ var_sudo }}"
  tasks:
  - include: common.yaml
  - name: fetch the Ambari yum repo (RedHat)
    when: ansible_os_family == 'RedHat'
    command: 'wget -nv http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.1.2/ambari.repo -O /etc/yum.repos.d/ambari.repo'
  - name: install the ambari agent (RedHat)
    when: ansible_os_family == 'RedHat'
    yum: name=ambari-agent state=latest
  - name: configure the ambari agent
    command: 'sed -i s/hostname=localhost/hostname={{ var_ambari_server }}/ /etc/ambari-agent/conf/ambari-agent.ini'
  - name: start the ambari agent
    command: 'ambari-agent start'
